### ISSUE TITLE
Missing Emojis

### ISSUE THREAD

**Issue by PKehnel** [Pustur/whatsapp-chat-parser-website#4]
![Emoji_issue](https://user-images.githubusercontent.com/23440847/110354470-7e466a80-8038-11eb-9bbd-aa25467db321.png)

Another minor issue is the detection of emojis. 
(Missing smileys classical-like thumbs up or normal smiley. )

**Comment by Pustur** [comment]
Can you tell me if it's fixed in this version? https://6046636a12be6d0007dc4599--whatsapp-chat-parser.netlify.app/

Thanks

**Comment by PKehnel** [comment]
Emoji issue still exists. 
![Emoji_issue2](https://user-images.githubusercontent.com/23440847/110365581-7fca5f80-8045-11eb-9743-21571ae66987.png)

Used txt: 
[WhatsApp Chat with Test.txt](https://github.com/Pustur/whatsapp-chat-parser-website/files/6103423/WhatsApp.Chat.with.Test.txt)

expected output: 
![Screenshot_20210308-193650](https://user-images.githubusercontent.com/23440847/110365844-cddf6300-8045-11eb-8200-9a16cf29a0ac.png)

**Comment by PKehnel** [comment]
btw nice tool and thanks for your work. Can also help you with these issues if you like. 

(last minor issue, detection of the chat owner, and placing his messages to the right, as in the original whatsapp chat)

**Comment by Pustur** [comment]
Sorry, I don't know what's the problem here, I downloaded your chat sample and I see them.

- Could you share your OS and browser?
- If you inspect the message can you see the emoji in the dev tools?
- Do you know if your system has a specific font for rendering emojis?

Just trying to understand what it could be...

**Comment by PKehnel** [comment]
You're right in both cases, seems to be an issue with my browser (outdated Chrome, Manjaro), as it works as expected with Firefox.   
For the view perspective, I think adding a button for this will litter your nice design and not really improve the overall experience.
